### ISSUE TITLE
Suggestion: add functional part to example

### ISSUE THREAD

**Issue by trsh** [setzer22/egui_node_graph#16]
For now as I understand the example is only for displaying the nodes visually. Would nice to have also demonstrated how to connect the functional part. Like doing the adding, substraction, etc.

**Comment by setzer22** [comment]
You're right, this library is meant to be very general, and there's many ways in which you could treat the graphs for more advanced use cases. But having a minimal evaluation example never hurts! I added code in the example to compute the result for the currently active node using a simple tree-walking strategy, the result is displayed in the top-left corner.

The new code is also commented in detail, let me know if you have any other suggestions about this, otherwise we can close :smile: 

Here's an example of how it looks:
![image](https://user-images.githubusercontent.com/7241990/159661243-f182ca46-53fe-4516-9bfd-30a37f07f95f.png)
