### ISSUE TITLE
Consider allowing properties to be both inputs and outputs at the same time

### ISSUE THREAD

**Issue by francesco-cattoglio** [setzer22/egui_node_graph#8]
Right now a Property can be either an Input or an Output, but not both. We should consider the option of allowing a property to be both an input and an output. This is used in the blueprint editor of UnrealEngine to declare the control flow of the script: 
[Blueprint example](https://docs.unrealengine.com/4.27/Images/ProgrammingAndScripting/Blueprints/UserGuide/FlowControl/Branch_Network.png)
To achieve this, we could unify `InputParam` and `OutputParam` structs, and instead differentiate between inputs and outputs in a new `ParamKind` enum (which would have many possible values, like `InputOnly`, `OutputOnly`, `InputOutput`, `InputOrConstant(ValueType)`, etc).

**Comment by setzer22** [comment]
What you're describing is the exact same data model I came up with when I started this. I ended up gravitating towards the current separate input/output system because this approach introduced several drawbacks. Here's the two main reasons I see in favor of the current design:

- When inputs and outputs are the same thing, there's more things that we'd need to check at runtime that were previously ensured at compile time. For instance, the type of `connections` becomes `SecondaryMap<ParamId, ParamId>`, so we can no longer ensure connections are a mapping from outputs to their inputs, and we need to introduce runtime checks for this.

- The current approach where the input also stores the constant is quite natural. Inputs are the pieces of data a node needs to run its "code" (whatever that means to the user). So when collecting those values, you read all your inputs, check for connections, and if no connection is there, take the constant instead. Once you introduce several variations of parameters you need to handle a lot more combinations.

As I see it, inputs and outputs logically represent the "port" (the tiny little circle where connections attach to), not the slot, so it makes sense that there's two of them. In the UE screenshot you shared, you could think of the control flow "slot" a pair of (input, output) parameters, which happen to be rendered at the same height. 

I think rendering different parameters at the same height can be seen as a presentation issue, and one that is easily solved. I don't think it's something that necessarily needs to be baked into the data model.

**Comment by francesco-cattoglio** [comment]
Perfect, thanks for the explanation of the design decision you made.

**Comment by setzer22** [comment]
It's good to put all this in writing, so thanks for asking the right questions :)
